### ISSUE TITLE
insert icons into my HTML page

### ISSUE THREAD

**Issue by THEOPHILEACHIZA** [THEOPHILEACHIZA/My-first-tutorial-project#3]
i had a problem last week how to insert icons into my HTML page.

**Comment by MichaelKentBurns** [comment]
As I said on issue #2, when you finish an issue, you should push all the work you have committed and comment in the issue that you have completed that.

It is also a good idea in that comment to note things like:

1) What difficulties you ran into, and how you overcame them.  Or if you have not solved them, what the problem is.   That allows me to see what problems you are having so I can give you some help.   
2) What you learned in the process.  
3) How you think the overall project is going.  Maybe just a sentence to indicate what is working and how you tested it.    

With all of those things, I can clone your repository and try out the work you have done.    

This process should be very collaborative and allow you and I to communicate each step of the way.  

Keep it up!
