### ISSUE TITLE
Put CSS in my HTML page

### ISSUE THREAD

**Issue by THEOPHILEACHIZA** [THEOPHILEACHIZA/My-first-tutorial-project#4]
I will put a similar background on my whole page; header, all the sections and footer. i will adjust the image, add the font, size  and center the text. center, color, and size the "Register" button. Adjust and size the icons in the footer.

**Comment by THEOPHILEACHIZA** [comment]
In this project, I learned and applied several CSS techniques to create a unique design and position elements in specific ways.
 
### Single background with background-image and background-color

To create a single background, I used the CSS properties `background-image` and `background-color`. I set a background image with `background-image` and a background color with `background-color`. This allowed me to create a custom background with an image and color that complement each other.

### Side-by-side positioning with float

To position an image and text side-by-side, I used the CSS property `float`. I applied `float: left` to the image to float it to the left, and `float: right` to the text to float it to the right. This created the effect of the two elements being positioned side-by-side.

 ### Stop Floating with Clear

To stop the footer icons from floating and make them appear below the floated elements, I used the CSS `clear` property. I applied `clear: both` to the footer icons, which forced them to appear below the previous floated elements, preventing them from floating themselves.

**Comment by THEOPHILEACHIZA** [comment]
As part of my recent exploration in CSS, I learned about the float and clear properties, which are essential for positioning elements on a web page. I've been digging deeper also into padding. By mastering padding, i was able to adjust the internal spacing of elements precisely, optimizing the appearance and user experience of our project.

Overall, I think the project is going well and progressing positively. While there are always challenges, we are moving in the right direction and making significant progress.

**Comment by MichaelKentBurns** [comment]
Can you go ahead and push your code so far?   
That will allow me to see your page live and inspect the CSS used to style it. 
Thanks.

**Comment by THEOPHILEACHIZA** [comment]
Thank you for your message, but I'm not sure I understand what you're
asking. Could you clarify what you mean by "pushing your code so far"? I'd
like to make sure I understand what I need to do.
Théophile
Video editor

**Comment by MichaelKentBurns** [comment]
When I look at your repository in GitHub, I see a nice README.md file.  Under the Code tab I see only the README.md file.   Under the Commits tab I see 3 commits, all of them of the README.md file.    Under the Issues tab I see 1 Issue that we are discussing in this conversation.    All that is good.  It shows me what your plan is for the project, and your first step in this Issue.     Everytime you have updated the README.md file and save the changes, it produces a Commit so that those changes are stored inside the git history of your repository.    Sometime in this process, you have to use command line git, or Git Desktop (VS Code) to clone the repository to your computer.   That creates a complete copy of the repository.  You can create issues and update the README.md file through GitHub on the web.  But, you can’t create files or edit them that way.   In order to do your development you use VS Code or other tools to create and edit .html and .css files in your repository.    Your issue seems to indicate that you are in the process of doing that, and that you have made some changes to those files.   Right?   Those files, and your changes don’t appear in the GitHub repository until you do two things.   First you commit some changes with a message indicating what you changed.  At that point the changes are still only on your computer, but safely recorded by git.  When you mention the changes you have made in your issue, you also need to use VS Code or git, or GitHub Desktop to push them to GitHub.   You can make a number of commits with their appropriate commit message, but nothing gets to GitHub until you do a push, and that will push all commits you have done since your last push.    Only then, can I see your work in the GitHub repository.  Does that make sense? Sent from my iPadOn Aug 31, 2024, at 20:24, Theophile Achiza ***@***.***> wrote:﻿
Thank you for your message, but I'm not sure I understand what you're

asking. Could you clarify what you mean by "pushing your code so far"? I'd

like to make sure I understand what I need to do.

Théophile

Video editor



Le dim. 1 sept. 2024, 01:04, Michael Kent Burns ***@***.***>

a écrit :

**Comment by THEOPHILEACHIZA** [comment]
Maybe it's me who made a mistake when I push for the first time. I have
pushed origin master while on my repository it's origin main. but I have
the possibility to change branch on my side to leave origin main to put
myself on origin master where there are all my projects that I pushed. or I
can still push this time to origin main? As you Can see on this screenshot.
Théophile
Video editor

**Comment by MichaelKentBurns** [comment]
Ah yes.  That problem comes up and is mysterious at first.  I think You can either:1 merge master into main, or 2 rename main to something else and then rename master to main. Let me clone it and see if I can do that in the clone.  Or you can try it, but make sure you have a clone first. Sent from my iPadOn Sep 1, 2024, at 12:22, Theophile Achiza ***@***.***> wrote:﻿
Maybe it's me who made a mistake when I push for the first time. I have

pushed origin master while on my repository it's origin main. but I have

the possibility to change branch on my side to leave origin main to put

myself on origin master where there are all my projects that I pushed. or I

can still push this time to origin main? As you Can see on this screenshot.

Théophile

Video editor



Le dim. 1 sept. 2024, 15:03, Michael Kent Burns ***@***.***>

a écrit :

**Comment by THEOPHILEACHIZA** [comment]
I tried to merge master into main but I didn't succeed sometimes it writes
unrelated histories.
Théophile
Video editor

**Comment by THEOPHILEACHIZA** [comment]
but what I just did, I put the master branch for default branch instead of
main.
Théophile
Video editor

Le lun. 2 sept. 2024, 17:11, Théophile Achiza ***@***.***> a
écrit :

**Comment by MichaelKentBurns** [comment]
OK, that works for me.Sent from my iPadOn Sep 2, 2024, at 10:17, Theophile Achiza ***@***.***> wrote:﻿
but what I just did, I put the master branch for default branch instead of

main.

Théophile

Video editor



Le lun. 2 sept. 2024, 17:11, Théophile Achiza ***@***.***> a

écrit :
